OD-675 [Fix] Adjusted length of the selected document
Fliplet/fliplet-widget-file-picker pull request #68
Opened 2021-12-03 09:13 UTC by skrupnyk

OD-675 https://weboo.atlassian.net/browse/OD-675

Backward compatibility
This change is fully backward compatible.

2021-12-06 12:24 UTC, tonytlwu requested changes

2021-12-06 12:24 UTC, tonytlwu commented on js/interface.js
> +      $(this).html(fileName.replace(fileName.match(/^.{20}(.*).{20}$/)[1], '...'));
```suggestion
      $(this).html(fileName.replace(fileName.match(/^.{20}(.*).{20}$/)[1], '&hellip;'));
```

2021-12-07 09:18 UTC, tonytlwu requested changes

2021-12-07 09:18 UTC, tonytlwu commented on js/interface.js
> +  $imagesContainer.find('.image-title').each(function () {
```js
  _.sortBy(folders, byLowerCaseName).forEach(addFolder);
  _.sortBy(files, byLowerCaseName).forEach(addFile);
```

These two lines are responsible for appending HTML onto the page. This new code is then changing the HTML on the page.

Instead of changing the HTML after they are already added to the page, can we make sure the HTML is correct when they are first appended onto the page? This should include the following:

1. Add a new Handlebars helper to format the file names, e.g. `{{ formatName name }}`
2. The helper will be responsible for assessing the names are returning a truncated version if necessary
3. Updating all the files and folder templates to use the new helper

@upplabs-alex-levchenko Let me know if more clarification is needed.

2021-12-09 15:50 UTC, OleksandrLavrynenko commented on js/interface.js
> +  $imagesContainer.find('.image-title').each(function () {
**@tonytlwu**  Hi! I suggest checking the names of files and folders before rendering them. How do you like this decision? This will only slightly expand the code and will not affect the functionality. 
![image](https://user-images.githubusercontent.com/86256215/145428973-0c845795-c435-450c-a5ef-633444a1c134.png)

2021-12-09 21:37 UTC, tonytlwu requested changes

2021-12-09 21:37 UTC, tonytlwu commented on js/interface.js
> +    debugger;
```suggestion
```

2021-12-09 21:37 UTC, tonytlwu commented on js/templates/document.interface.hbs
> +  <div class="image-title">{{ formatName name}}</div>
```suggestion
  <div class="image-title">{{ formatName name }}</div>
```

2021-12-09 21:37 UTC, tonytlwu commented on js/templates/folder.interface.hbs
> +  <div class="image-title">{{ formatName name}}</div>
```suggestion
  <div class="image-title">{{ formatName name }}</div>
```

2021-12-10 12:48 UTC, tonytlwu requested changes

2021-12-10 12:48 UTC, tonytlwu commented on js/interface.js
> +  $imagesContainer.find('.image-title').each(function () {
Why is this part still necessary when the titles are being rendered using the new Handlebars template? This feels like an unnecessary loop of DOM changes.

2021-12-10 13:29 UTC, skrupnyk commented
https://github.com/Fliplet/fliplet-widget-file-picker/pull/68#discussion_r766651555

This part is no longer needed and has been removed.

2021-12-10 13:29 UTC, skrupnyk commented on js/interface.js
> +  $imagesContainer.find('.image-title').each(function () {
> Why is this part still necessary when the titles are being rendered using the new Handlebars template? This feels like an unnecessary loop of DOM changes.

This part is no longer needed and has been removed.

2021-12-10 14:28 UTC, tonytlwu approved these changes
@romanyosyfiv @inna-bieshulia This is ready for testing

Risk: Medium
Affected: Folders and files listed in file pickers
Verify: Folder and file names are correctly displayed

Squash and merge: Use PR title

2021-12-10 14:45 UTC, merged